Add autofocus param to textarea
oconn/reagent-form pull request #4
Opened 2019-01-31 17:07 UTC by mitchgillin

Allows users to specify a param to autofocus on an input.

2019-01-31 21:44 UTC, dehli commented on src/cljs/reagent_form/components/input.cljs
> +                   (true? autofocus))
Should this be `auto-focus`?

2019-01-31 21:53 UTC, mitchgillin commented on src/cljs/reagent_form/components/input.cljs
> +                   (true? autofocus))
Yes ... 🤦‍♂️

2019-02-01 16:10 UTC, oconn requested changes

2019-02-01 16:10 UTC, oconn commented on src/cljs/reagent_form/components/input.cljs
> +              (and (= type :textarea)
We should allow regular inputs to specify `auto-focus` as well

2019-02-04 20:26 UTC, merged